# Generated by Django 5.0.6 on 2024-05-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroGuitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Синий', 'Синий'), ('Черный', 'Черный'), ('Белый', 'Белый'), ('Серый', 'Серый')], max_length=20)),
                ('form', models.CharField(blank=True, choices=[('Телекастер', 'Телекастер'), ('Леспол', 'Леспол'), ('Суперстрат', ' Суперстрат'), ('СГ', 'СГ'), ('Эксплорер', 'Эксплорер'), ('Стратокастер', 'Стратокастер')], max_length=20)),
                ('brand', models.CharField(blank=True, choices=[('Yamaha', 'Yamaha'), ('Ibanez', 'Ibanez'), ('Fender', 'Fender'), ('Gibson', 'Gibson')], max_length=20)),
            ],
        ),
    ]
